<a href="https://colab.research.google.com/github/bhuvaneshraja-10/bhuvanesh/blob/main/numpyday2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr =  np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
import numpy as np
arr =  np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [5]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2),axis = 1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [6]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2),axis = 0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [9]:
import random
x = random.randint(3,5)
print(x)


3


In [11]:
from numpy import random
x = random.choice([3,5,7,9],size = (3,5))
print(x)

[[7 5 7 9 9]
 [5 9 9 7 3]
 [7 9 3 7 3]]
