<a href="https://colab.research.google.com/github/bhuvaneshraja-10/bhuvanesh/blob/main/numpybasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
arr = np.array(1)
print(arr)
print(type(arr))

1
<class 'numpy.ndarray'>


In [4]:
import numpy as np
arr = np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
import numpy as np
arr = np.array([[1,2,3],[1,2,3]])
print(arr)
print( type(arr))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [9]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2])
print(arr.ndim)
print(type(arr))

3
1
<class 'numpy.ndarray'>


In [10]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2] + arr[3])

7


In [11]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,4])

10


In [12]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,4])

5


In [13]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [15]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [21]:
var = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]]])
print(var[0,0,0],var[0,1,0],var[0,2,0])

1 4 7


In [24]:
b = np.array([1,2,3,4,5])
x = b.copy()
b[0] = 12

print(x)
print(b)

[1 2 3 4 5]
[12  2  3  4  5]


In [26]:
 d =np.array([1,2,3,4,5])
 c = d.view()
 d[0] = 12

 print(d)
 print(c)

[12  2  3  4  5]
[12  2  3  4  5]
